name: Production Release

on:
  push:
    tags:
      - "v*.*.*" # Trigger for all version tags

permissions:
  contents: write

jobs:
  release:
    if: "! contains(github.ref_name, '-rc')" # Only run if the tag does not include `-rc`
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.6

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Run Tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: go test ./...

      - name: Release info
        run: echo "Production release workflow triggered for ${{ github.ref_name }}"
